# Generated by Django 3.0.3 on 2022-02-03 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신일자')),
                ('object_id', models.PositiveIntegerField(verbose_name='관련 데이터 번호')),
                ('body', models.TextField(verbose_name='댓글내용')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_type_comment', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
