# Generated by Django 3.0.3 on 2022-01-21 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from board.gen_article import gen_master_article


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('body', models.TextField(verbose_name='내용')),
                ('one_source', models.CharField(max_length=200, verbose_name='출처명')),
                ('information_source', models.CharField(blank=True, max_length=200, verbose_name='출처링크')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.RunPython(gen_master_article),
    ]
