# Generated by Django 3.0.3 on 2022-01-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_article_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_type',
        ),
    ]
