# Generated by Django 3.0.3 on 2022-01-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_article_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='information_source',
            field=models.CharField(max_length=200, verbose_name='출처링크'),
        ),
        migrations.AlterField(
            model_name='article',
            name='one_source',
            field=models.CharField(max_length=200, verbose_name='출처명'),
        ),
    ]
