# Generated by Django 3.0.3 on 2022-01-25 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20220124_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
