# Generated by Django 3.0.3 on 2022-01-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20220120_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='information_source',
            field=models.CharField(blank=True, max_length=200, verbose_name='출처링크'),
        ),
    ]
